// GENERATED by scripts/sync-runtime.mjs; edit packages/core/src instead.
const { clamp } = require('./math.js');

/** 公开治理评分仅作反馈，不作为失败条件；隐藏人格值不参与计算。 */
function governanceScore(state) {
  const stats = state.stats;
  const parts = {
    treasury: clamp(state.treasury / (Math.max(1, stats.total) * state.cfg.grainNeed * 20), 0, 1) * 35,
    satisfaction: clamp((stats.avgSatisfaction + 30) / 60, 0, 1) * 35,
    population: clamp(stats.total / 800, 0, 1) * 20,
    intelligence: clamp(stats.avgIntelligence / 100, 0, 1) * 10,
  };
  return { total: Math.round(Object.values(parts).reduce((a,b) => a+b, 0)), parts };
}

module.exports = { governanceScore };
