const { OFFICIAL_ROLE } = require('./config.js');
const SUPPLY_COST=[0,5,10,18], EQUIPMENT_COST=[0,8,18,34];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const clampInt=(x,a,b)=>Math.round(clamp(Number(x)||a,a,b));
function eligibleConscripts(people){return people.filter(p=>!p.isCriminal&&p.age>=18&&p.age<=50);}
function estimateWarCost(state,plan){plan=plan||{};const rate=clamp(Number(plan.conscriptionRate)||.2,.05,.5),supply=clampInt(plan.supplyLevel,1,3),equipment=clampInt(plan.equipmentLevel,1,3),eligible=eligibleConscripts(state.people).length,troops=eligible?Math.max(1,Math.round(eligible*rate)):0,perTroop=2+SUPPLY_COST[supply]+EQUIPMENT_COST[equipment];return{troops,perTroop,total:troops*perTroop,supply,equipment,rate};}
function maybeStartWar(state){if(state.year<20||state.pendingWar||state.treaty)return null;if(state.lastWarYear!=null&&state.year-state.lastWarYear<4)return null;const eligible=eligibleConscripts(state.people).length;if(eligible<8||!state.rng.chance(.2))return null;const enemies=['北境联盟','河西公国','东岭王国','南海诸侯'];state.pendingWar={id:`war_${state.year}`,year:state.year,enemyName:state.rng.pick(enemies),enemyStrength:Math.max(6,Math.round(eligible*state.rng.uniform(.18,.55))),eligible,offeredTreaty:createTreaty(state,false)};return state.pendingWar;}
function applyWarDecision(state,decision){const war=state.pendingWar;if(!war)return null;decision=decision||{};let result;if(decision.action==='surrender')result=surrender(state,war);else if(decision.action==='treaty')result=signTreaty(state,war,war.offeredTreaty);else result=fight(state,war,decision);state.lastWarYear=state.year;state.warHistory=state.warHistory||[];state.warHistory.push(result);if(state.warHistory.length>40)state.warHistory.shift();state.pendingWar=null;return result;}
function treatyTaxFloor(state){return treatyActive(state)?(state.treaty.minTaxRate||0):0;}
function enforceTreatyTaxFloor(state,log){if(state.treaty&&state.year>state.treaty.endYear){if(log)log.push('📜 对外赔款条约期满，税率限制解除');state.treaty=null;return;}const floor=treatyTaxFloor(state);if(!floor)return;let changed=false;['farmer','worker','merchant'].forEach(k=>{if(state.policy.tax[k]<floor){state.policy.tax[k]=floor;changed=true;}});if(changed&&log)log.push(`📜 条约要求税率不得低于 ${(floor*100).toFixed(0)}%，已自动调整`);}
function settleTreatyTax(state,taxRevenue,log){if(!treatyActive(state))return taxRevenue;const taxPayment=taxRevenue*(state.treaty.taxShare||0),payment=taxPayment+(state.treaty.annualFlat||0);if(log)log.push(`🏳 条约赔款 -${payment.toFixed(1)}（税收分成 ${taxPayment.toFixed(1)}）`);return taxRevenue-payment;}
function fight(state,war,d){const plan=estimateWarCost(state,d);state.treasury-=plan.total;const assigned=state.people.filter(p=>!p.isCriminal&&p.role===OFFICIAL_ROLE.MILITARY).length,available=state.people.filter(p=>!p.isCriminal&&p.klass==='official').length,officers=state.year>=21?Math.max(assigned,Math.min(available,state.policy.officials.military||0)):assigned,command=1+Math.min(15,officers)*.025,preparedness=1+Math.min(.3,(state.policy.militaryRatio||0)*.6),readiness=.55+plan.supply*.3+plan.equipment*.4,power=plan.troops*readiness*command*preparedness*state.rng.uniform(.88,1.12),ratio=power/Math.max(1,war.enemyStrength);let outcome,rate,sat;if(ratio>=1.2){outcome='victory';rate=state.rng.uniform(.12,.22);sat=2;}else if(ratio>=.85){outcome='costly_victory';rate=state.rng.uniform(.26,.4);sat=.5;}else{outcome='defeat';rate=state.rng.uniform(.5,.7);sat=-4;}const casualties=removeRandomPeople(state,eligibleConscripts(state.people),Math.round(plan.troops*rate));let civilianCasualties=0,treaty=null,reward=0;if(outcome==='defeat'){civilianCasualties=removeRandomPeople(state,state.people.filter(p=>!p.isCriminal),Math.round(state.people.length*state.rng.uniform(.01,.035)));treaty=createTreaty(state,true);activateTreaty(state,treaty);}else{reward=Math.round(Math.min(plan.total*.3,war.enemyStrength*3));state.treasury+=reward;}state.people.forEach(p=>{if(!p.isCriminal)p.satisfaction+=sat;});const label=outcome==='victory'?'胜利':outcome==='costly_victory'?'惨胜':'战败';state.log.push(`⚔ 对${war.enemyName}战争${label}：征兵 ${plan.troops}，军费 ${plan.total.toFixed(0)}，阵亡 ${casualties}${civilianCasualties?`，平民死亡 ${civilianCasualties}`:''}${reward?`，战利品 ${reward}`:''}`);return{year:state.year,action:'fight',outcome,troops:plan.troops,cost:plan.total,casualties,civilianCasualties,reward,treaty};}
function surrender(state,war){const payment=Math.round(Math.max(300,state.people.length*4,Math.max(0,state.treasury)*.3));state.treasury-=payment;state.people.forEach(p=>{if(!p.isCriminal)p.satisfaction-=3;});state.log.push(`🏳 向${war.enemyName}投降，直接赔款 ${payment}`);return{year:state.year,action:'surrender',outcome:'surrender',cost:payment,casualties:0};}
function signTreaty(state,war,treaty){activateTreaty(state,treaty);state.people.forEach(p=>{if(!p.isCriminal)p.satisfaction-=1.5;});state.log.push(`📜 与${war.enemyName}签订 ${treaty.duration} 年赔款条约：立即赔款 ${treaty.upfront}，每年固定 ${treaty.annualFlat}${treaty.taxShare?` + 税收 ${(treaty.taxShare*100).toFixed(0)}%`:''}${treaty.minTaxRate?`，税率不得低于 ${(treaty.minTaxRate*100).toFixed(0)}%`:''}`);return{year:state.year,action:'treaty',outcome:'treaty',cost:treaty.upfront,casualties:0,treaty:Object.assign({},treaty)};}
function createTreaty(state,punitive){const duration=state.rng.int(punitive?5:3,punitive?8:6),hasTax=state.rng.chance(punitive?.9:.65),treasury=Math.max(0,state.treasury);return{duration,upfront:Math.round(Math.max(punitive?250:120,treasury*(punitive?.16:.08))),annualFlat:Math.round(Math.max(40,state.people.length*(punitive?.5:.3))),taxShare:hasTax:+state.rng.uniform(punitive?.3:.2,punitive?.5:.4).toFixed(2):0,minTaxRate:hasTax?state.rng.int(punitive?8:5,punitive?16:13)/100:0};}
function activateTreaty(state,treaty){state.treasury-=treaty.upfront;state.treaty=Object.assign({},treaty,{startYear:state.year,endYear:state.year+treaty.duration-1});enforceTreatyTaxFloor(state,state.log);}
function treatyActive(state){return Boolean(state.treaty&&state.year<=state.treaty.endYear);}
function removeRandomPeople(state,candidates,count){let removed=0,pool=candidates.slice();while(removed<count&&pool.length){const p=pool.splice(state.rng.int(0,pool.length-1),1)[0],i=state.people.indexOf(p);if(i>=0){state.people.splice(i,1);removed++;}}return removed;}
module.exports={eligibleConscripts,estimateWarCost,maybeStartWar,applyWarDecision,treatyTaxFloor,enforceTreatyTaxFloor,settleTreatyTax};
