// 核心为唯一模拟来源：生成小程序 CommonJS 镜像与无需服务器的单文件包。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const modules = ['config','math','person','economy','society','government','score','events','war','game'];
let bundle = '// GENERATED by scripts/sync-runtime.mjs; edit packages/core/src instead.\nconst GameCore = {};\n';
for (const name of modules) {
  const source = fs.readFileSync(path.join(root, 'packages/core/src', name + '.js'), 'utf8');
  const names = [...source.matchAll(/export\s+(?:const|class|function)\s+(\w+)/g)].map(m => m[1]);
  for (const match of source.matchAll(/export\s*\{([^}]+)\};?/g)) names.push(...match[1].split(',').map(x => x.trim()));
  const exports = [...new Set(names)].join(', ');
  const stripped = source.replace(/export\s*\{[^}]+\};?/g, '').replace(/export\s+(?=const|class|function)/g, '');
  const imports = (text, mode) => text.replace(/import\s*\{([^}]+)\}\s*from\s*['"]\.\/(\w+)\.js['"];?/g,
    (_, fields, dep) => `const {${fields.replace(/\s+as\s+/g, ': ')}} = ${mode === 'cjs' ? `require('./${dep}.js')` : `GameCore.${dep}`};`);
  const cjs = '// GENERATED by scripts/sync-runtime.mjs; edit packages/core/src instead.\n' + imports(stripped,'cjs') + `\nmodule.exports = { ${exports} };\n`;
  const target = path.join(root, 'apps/miniprogram/core', name + '.js');
  if (!fs.existsSync(target) || fs.readFileSync(target,'utf8') !== cjs) fs.writeFileSync(target, cjs);
  bundle += `GameCore.${name} = (() => {\n${imports(stripped,'bundle')}\nreturn { ${exports} };\n})();\n`;
}
const transition = fs.readFileSync(path.join(root, 'apps/web/scripts/year-transition.js'), 'utf8').replace('export function', 'function');
bundle += transition;
const target = path.join(root, 'play.html');
let html = fs.readFileSync(target, 'utf8');
// 替换旧的手写模拟副本；后续构建只同步标记内的适配代码。
const adapter = fs.readFileSync(path.join(root,'scripts/standalone-runtime.js'),'utf8');
// 将旧的单行 UI 函数迁入可维护的适配层（下次同步不再匹配）。
html = html.replace(/^    function (showEvent|renderPeople)\(\).*\r?\n/gm, '');
html = html.replace(/let key=state\.log\[0\][^\n]*?while\(log.children.length>30\)log.removeChild\(log.lastChild\);/, 'appendYearLog();');
const adapterStart = html.includes('// BEGIN STANDALONE ADAPTER') ? html.indexOf('// BEGIN STANDALONE ADAPTER') : html.indexOf('    const C=');
const adapterEnd = html.indexOf('    function signed', adapterStart);
if (adapterStart < 0 || adapterEnd < 0) throw new Error('Standalone adapter boundaries not found');
html = html.slice(0,adapterStart) + '// BEGIN STANDALONE ADAPTER\n' + adapter + '// END STANDALONE ADAPTER\n' + html.slice(adapterEnd);
html = html.replace(/let o=JSON\.parse\(saved\);[\s\S]*?state=GameCore\.game\.deserialize\(JSON\.stringify\(o\)\);withCore\(\(\)=>\{\}\);/, 'loadStandaloneSave(saved);');
html = html.replace("let available=state.people.filter(p=>p.klass==='official'&&!p.isCriminal).length", "let available=state.people.filter(p=>p.klass==='official'&&!p.isCriminal&&p.age>=18).length");
const marker = /<!-- BEGIN GENERATED CORE -->[\s\S]*?<!-- END GENERATED CORE -->\s*/;
html = html.replace(marker, '');
html = html.replace('  <script>','  <!-- BEGIN GENERATED CORE -->\n  <script>\n' + bundle.replace(/<\/script/gi, '<\\/script') + '\n  </script>\n  <!-- END GENERATED CORE -->\n  <script>');
const presentationCSS = fs.readFileSync(path.join(root, 'apps/web/styles/presentation.css'), 'utf8');
html = html.replace(/<!-- BEGIN PRESENTATION CSS -->[\s\S]*?<!-- END PRESENTATION CSS -->\s*/, '');
html = html.replace('</head>', '<!-- BEGIN PRESENTATION CSS -->\n<style>\n' + presentationCSS + '\n</style>\n<!-- END PRESENTATION CSS -->\n</head>');
fs.writeFileSync(target, html);
console.log('Synced 10 CommonJS modules and standalone core/transition bundle.');
